### ISSUE TITLE
Lack of header file <ur_arm/Joints.h>  and <ur_arm/SetDigitalOut.h>

### ISSUE THREAD

**Issue by Chunting** [wcaarls/ur_arm#1]
Hi Wcaarls:
I am terested in your project for UR5, after I cloned it , I did not find the header files "Joint.h" and SetDigitalOut.h".
Would you please add them? 
If you can give me some directions on how to run it, I will appreciate it.

Thanks,
Chunting

**Comment by wcaarls** [comment]
Hi Chunting,

This package is meant to be compiled under rosbuild, which automatically generates these header files. However, ROS has moved on (to catkin) and so has the UR5 firmware, so you might have more luck with a different driver, such as the ur_modern_driver:

https://github.com/ThomasTimm/ur_modern_driver

Cheers,

Wouter.
